name: paginationList
description: A Powerful Flutter Pagination Library with loading indicator at bottom.
version: 0.0.1
homepage: https://github.com/sanket-vekariya/paginationList
authors:
  - Sanket Vekariya <ssvekariya11@gmail.com>
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true